version: "2.1"

services:
  # Behat
  behat:
    hostname: behat
    image: docksal/behat
    volumes:
      - ${PROJECT_ROOT}/tests/behat:/src
    # Keep the container running
    entrypoint: "top -b"

  # Selenium
  browser:
    hostname: browser
    # Pick/uncomment one
    image: selenium/standalone-chrome-debug:3.141.59-oxygen
    #image: selenium/standalone-firefox
    ports:
      - "5900:5900"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}