version: "2.1"

services:
  # Web
  web:
    hostname: web
    image: docksal/web:2.1-apache2.4
    volumes:
      - project_root:/var/www:ro,nocopy  # Project root volume
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
    environment:
      - APACHE_DOCUMENTROOT=/var/www/${DOCROOT:-docroot}
      - APACHE_BASIC_AUTH_USER
      - APACHE_BASIC_AUTH_PASS
    depends_on:
      - cli
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # DB
  db:
    hostname: db
    ports:
      - "${MYSQL_PORT_MAPPING:-3306}"
    volumes:
      - project_root:/var/www:ro,nocopy  # Project root volume
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
    command: "--datadir /var/lib/mysql-sandbox"

  # CLI - Used for all console commands and tools.
  cli:
    hostname: cli
    image: czietlow/service-cli:2.2-php7.1--with-phantomjs
    volumes:
      - project_root:/var/www:rw,nocopy  # Project root volume
      - docksal_ssh_agent:/.ssh-agent:ro  # Shared ssh-agent socket
    environment:
      - HOST_UID
      - HOST_GID
      - DOCROOT
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
      - XDEBUG_CONFIG=remote_connect_back=0 remote_host=${DOCKSAL_HOST_IP}  # Point xdebug to the host IP
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Behat
  behat:
    hostname: behat
    image: docksal/behat
    volumes:
      - ${PROJECT_ROOT}/tests/behat:/src
    # Keep the container running
    entrypoint: "top -b"

  # Selenium
  browser:
    hostname: browser
    # Pick/uncomment one
    image: selenium/standalone-chrome-debug
    #image: selenium/standalone-firefox
    ports:
      - "5900:5900"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}